# Spring Cloud Gateway port
server:
  port: 8080  // spring cloud gateway가 동작하는 port 번호

spring:
  cloud:
    gateway:
    default-filters:  //  spring cloud gateway 공통 filter
      - name: GlobalFilter
        args:
         baseMessage: Spring Cloud Gateway GlobalFilter
         preLogger: true
         postLogger: true
    # MSA 라우팅 정의
    routes:
      - id: member_service
        uri: http://localhost:8081  //목적지
        predicates:  //조건부 집합 Header나 Parameter같은 HTTP 요청의 모든 항목 비교
         - Path=/member/**
        filters:
         - name: MemberFilter
           args:
             baseMessage: MemberFilter
             preLogger: true
             postLogger: true
        //localhost:8080/member/ 주소로 서비스가 유입되면 member_service 호출 > localhost:8081/user로 라우팅 된다. *과정에서 globalfilter를 거침
