server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, httptrace, busrefresh

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://bbleureka-env.eba-sk7czfia.ap-northeast-2.elasticbeanstalk.com/eureka

spring:
  application:
    name: bbl-gateway

  profiles:
    active: dev

  cloud:
    config:
      name: application

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  config:
    import: configserver:http://ec2-13-124-49-255.ap-northeast-2.compute.amazonaws.com:8888/

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

    gateway:
      default-filters:
        - name: GlobalFilter
          args:
           baseMessage: Spring Cloud Gateway GlobalFilter
           preLogger: true
           postLogger: true
      routes:
        - id: bbl-member
          uri: lb://BBL-MEMBER
          predicates:
            - Path=/bbl-member/members/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/bbl-member/(?<segment>.*), /$\{segment}
            - MemberFilter

        - id: bbl-member
          uri: lb://BBL-MEMBER
          predicates:
            - Path=/bbl-member/members/signUp
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/bbl-member/(?<segment>.*), /$\{segment}
            - MemberFilter

        - id: bbl-member
          uri: lb://BBL-MEMBER
          predicates:
            - Path=/bbl-member/members/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/bbl-member/(?<segment>.*), /$\{segment}
            - name: MemberFilter
            - name: JwtAuthorizationHeaderFilter

        - id: bbl-member
          uri: lb://BBL-MEMBER
          predicates:
            - Path=/bbl-member/actuator/**
            - Method=POST,GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/bbl-member/(?<segment>.*), /$\{segment}
            - name: MemberFilter

        - id: bbl-member
          uri: lb://BBL-MEMBER
          predicates:
            - Path=/bbl-member/tests/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/bbl-member/(?<segment>.*), /$\{segment}
            - name: MemberFilter

#        - id: bbl-payment
#          uri: lb://BBL-PAYMENT
#          predicates:
#            - Path=/bbl-payment/payments/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/bbl-payment/(?<segment>.*), /$\{segment}
#            - CustomFilter

#        - id: bbl-career
#          uri: lb://BBL-CAREER
#          predicates:
#            - Path=/bbl-career/careers/**
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/bbl-career/(?<segment>.*), /$\{segment}
#            - CustomFilter